{% set name = "aurorafusion" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 348014966408e20d5744e8f63bf6916c5d9fca6df9b035f8f79a5037f8e682b3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - numpy
    - scipy
    - matplotlib
    - pexpect
    - requests
    - pandas

  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - pexpect
    - requests
    - pandas

test:
  imports:
    - aurora

about:
  home: https://aurora-fusion.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: USER_AGREEMENT.txt
  summary: Modern toolbox for impurity transport, neutrals and radiation modeling in fusion plasmas
  description: |
    Aurora is a package to simulate heavy-ion transport, neutrals and radiation in magnetically-confined plasmas.
    It offers a 1.5D impurity transport forward model inheriting from the historical STRAHL code,
    with which it has been thoroughly benchmarked. Routines to analyze neutral states of hydrogen
    isotopes, both from the edge of fusion plasmas and from neutral beam injection, allow integration
    of impurity and neutral transport analysis.
    Aurora’s code is mostly written in Python 3, with fast low-level components om Fortran90 and Julia.
    The package enables radiation calculations using ADAS atomic rates, which can easily be applied
    to the output of Aurora’s own forward model, or coupled with other 1D, 2D or 3D transport codes.
  doc_url: https://aurora-fusion.readthedocs.io/
  dev_url: https://github.com/fsciortino/aurora

extra:
  recipe-maintainers:
    - fsciortino
